name: fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  fluttertoast: ^8.2.12

  # 🔹 Firebase (latest stable)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0   # ✅ only once

  # 🔹 Media
  image_picker: ^1.0.4

  # 🔹 Map plugins
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  # flutter_map_cancellable_tile_provider → 🚫 remove (discontinued)

  # 🔹 Device preview & Auth
  device_preview: ^1.3.1
  flutter_facebook_auth: ^7.1.2
  flutter_web_auth_2: ^4.1.0

  # 🔹 Utils & Icons
  http: ^1.5.0
  font_awesome_flutter: ^10.10.0
  iconsax: ^0.0.8
  flutter_map_cancellable_tile_provider: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:

